#=========================
# Tomcat Namesapce Deployment
#=========================
apiVersion: v1
kind: Namespace
metadata:
  name: tomcat-namespace-nautilus


---
#=========================
# Tomcat Deployment
#=========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment-nautilus
  namespace: tomcat-namespace-nautilus
  labels:
    app: tomcat-deployment-nautilus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat-deployment-nautilus
  template:
    metadata:
      labels:
        app: tomcat-deployment-nautilus
    spec:
      containers:
      - name: tomcat-container-nautilus
        image: gcr.io/kodekloud/centos-ssh-enabled:tomcat
        ports:
        - containerPort: 8080
---
#=========================
# Tomcat Service 
#=========================
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service-nautilus
  namespace: tomcat-namespace-nautilus
spec:
  selector:
    app: tomcat-deployment-nautilus
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 32227
