services:
  web:
    image: php:apache
    container_name: php_apache
    ports:
      - 6200:80
    volumes:
      - /var/www/html:/var/www/html
    depends_on:
      - db

  db:
   image: mariadb:latest
   container_name: mysql_apache
   environment: 
     - MYSQL_DATABASE=database_apache
     - MYSQL_USER=banner
     - MYSQL_PASSWORD=BigGr33n 
     - MARIADB_ROOT_PASSWORD=YourSecureRootPassword
   ports:
     - 3306:3306
   volumes:   
     - /var/lib/mysql:/var/lib/mysql