apiVersion: v1
kind: Pod
metadata:
  name: time-check
  labels:
    app: time-check
  namespace: nautilus
spec:
  volumes:
  - name: log-volume
    emptyDir: {}
  containers:
  - image: busybox:latest
    name: time-check
    env:
    - name: TIME_FREQ
      valueFrom:
        configMapKeyRef:
          name: time-config
          key: TIME_FREQ
    command: ["/bin/sh", "-c"]
    args:
    - while true; do date >> /opt/sysops/time/time-check.log; sleep $TIME_FREQ; done
    volumeMounts:
    - name: log-volume
      mountPath: /opt/sysops/time
  restartPolicy: Always